version: "3.9"
services:

  app:
    image: core-payment-lesson-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    networks:
      app-net-1:

  postgres:
    image: postgres:14.3-alpine3.16
    environment:
      POSTGRES_DB: "payservice-db"
      POSTGRES_USER: "payservice"
      POSTGRES_PASSWORD: "payservice"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app-net-1:

networks:
  app-net-1:
    external: true