version: "3.9"

networks:
  app-net-1:
    external: true

services:
  pay:
    image: pay-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    ports:
      - "50051:50051"
    networks:
      - app-net-1

  postgres:
    image: postgres:14.3-alpine3.16
    environment:
      POSTGRES_DB: "payservice-db"
      POSTGRES_USER: "payservice"
      POSTGRES_PASSWORD: "payservice"
#      PGDATA: "/var/lib/postgresql/data/pgdata"
#    volumes:
#      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net-1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    healthcheck:
      test: ["CMD","wget","-O-","localhost:14269"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net-1
