// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargeRequestMessage_CreditCard_ExpMonth int32

const (
	ChargeRequestMessage_CreditCard_JAN ChargeRequestMessage_CreditCard_ExpMonth = 0
	ChargeRequestMessage_CreditCard_FEB ChargeRequestMessage_CreditCard_ExpMonth = 1
	ChargeRequestMessage_CreditCard_MAR ChargeRequestMessage_CreditCard_ExpMonth = 2
	ChargeRequestMessage_CreditCard_APR ChargeRequestMessage_CreditCard_ExpMonth = 3
	ChargeRequestMessage_CreditCard_MAY ChargeRequestMessage_CreditCard_ExpMonth = 4
	ChargeRequestMessage_CreditCard_JUN ChargeRequestMessage_CreditCard_ExpMonth = 5
	ChargeRequestMessage_CreditCard_JUL ChargeRequestMessage_CreditCard_ExpMonth = 6
	ChargeRequestMessage_CreditCard_AUG ChargeRequestMessage_CreditCard_ExpMonth = 7
	ChargeRequestMessage_CreditCard_SEP ChargeRequestMessage_CreditCard_ExpMonth = 8
	ChargeRequestMessage_CreditCard_OCT ChargeRequestMessage_CreditCard_ExpMonth = 9
	ChargeRequestMessage_CreditCard_NOV ChargeRequestMessage_CreditCard_ExpMonth = 10
	ChargeRequestMessage_CreditCard_DEC ChargeRequestMessage_CreditCard_ExpMonth = 11
)

// Enum value maps for ChargeRequestMessage_CreditCard_ExpMonth.
var (
	ChargeRequestMessage_CreditCard_ExpMonth_name = map[int32]string{
		0:  "JAN",
		1:  "FEB",
		2:  "MAR",
		3:  "APR",
		4:  "MAY",
		5:  "JUN",
		6:  "JUL",
		7:  "AUG",
		8:  "SEP",
		9:  "OCT",
		10: "NOV",
		11: "DEC",
	}
	ChargeRequestMessage_CreditCard_ExpMonth_value = map[string]int32{
		"JAN": 0,
		"FEB": 1,
		"MAR": 2,
		"APR": 3,
		"MAY": 4,
		"JUN": 5,
		"JUL": 6,
		"AUG": 7,
		"SEP": 8,
		"OCT": 9,
		"NOV": 10,
		"DEC": 11,
	}
)

func (x ChargeRequestMessage_CreditCard_ExpMonth) Enum() *ChargeRequestMessage_CreditCard_ExpMonth {
	p := new(ChargeRequestMessage_CreditCard_ExpMonth)
	*p = x
	return p
}

func (x ChargeRequestMessage_CreditCard_ExpMonth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargeRequestMessage_CreditCard_ExpMonth) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (ChargeRequestMessage_CreditCard_ExpMonth) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x ChargeRequestMessage_CreditCard_ExpMonth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargeRequestMessage_CreditCard_ExpMonth.Descriptor instead.
func (ChargeRequestMessage_CreditCard_ExpMonth) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0, 0, 0}
}

type ChargeRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount      int64                            `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency    string                           `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	TerminalId  string                           `protobuf:"bytes,3,opt,name=terminalId,proto3" json:"terminalId,omitempty"`
	InvoiceId   string                           `protobuf:"bytes,4,opt,name=invoiceId,proto3" json:"invoiceId,omitempty"`
	Description string                           `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreditCard  *ChargeRequestMessage_CreditCard `protobuf:"bytes,6,opt,name=creditCard,proto3" json:"creditCard,omitempty"`
}

func (x *ChargeRequestMessage) Reset() {
	*x = ChargeRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequestMessage) ProtoMessage() {}

func (x *ChargeRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequestMessage.ProtoReflect.Descriptor instead.
func (*ChargeRequestMessage) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *ChargeRequestMessage) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ChargeRequestMessage) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ChargeRequestMessage) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *ChargeRequestMessage) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *ChargeRequestMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChargeRequestMessage) GetCreditCard() *ChargeRequestMessage_CreditCard {
	if x != nil {
		return x.CreditCard
	}
	return nil
}

type ChargeResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32                          `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusName string                         `protobuf:"bytes,2,opt,name=statusName,proto3" json:"statusName,omitempty"`
	Uuid       string                         `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ReceiptUrl string                         `protobuf:"bytes,4,opt,name=receiptUrl,proto3" json:"receiptUrl,omitempty"`
	Message    string                         `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	ThreeDs    *ChargeResponseMessage_ThreeDs `protobuf:"bytes,6,opt,name=threeDs,proto3" json:"threeDs,omitempty"`
}

func (x *ChargeResponseMessage) Reset() {
	*x = ChargeResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeResponseMessage) ProtoMessage() {}

func (x *ChargeResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeResponseMessage.ProtoReflect.Descriptor instead.
func (*ChargeResponseMessage) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *ChargeResponseMessage) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ChargeResponseMessage) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *ChargeResponseMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ChargeResponseMessage) GetReceiptUrl() string {
	if x != nil {
		return x.ReceiptUrl
	}
	return ""
}

func (x *ChargeResponseMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChargeResponseMessage) GetThreeDs() *ChargeResponseMessage_ThreeDs {
	if x != nil {
		return x.ThreeDs
	}
	return nil
}

type ChargeRequestMessage_CreditCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number                       string                                   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	VerificationValue            string                                   `protobuf:"bytes,2,opt,name=verificationValue,proto3" json:"verificationValue,omitempty"`
	Holder                       string                                   `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	ExpMonth                     ChargeRequestMessage_CreditCard_ExpMonth `protobuf:"varint,4,opt,name=expMonth,proto3,enum=server.ChargeRequestMessage_CreditCard_ExpMonth" json:"expMonth,omitempty"`
	ExpYear                      string                                   `protobuf:"bytes,5,opt,name=expYear,proto3" json:"expYear,omitempty"`
	Token                        string                                   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	SkipThreeDSecureVerification bool                                     `protobuf:"varint,7,opt,name=skipThreeDSecureVerification,proto3" json:"skipThreeDSecureVerification,omitempty"`
}

func (x *ChargeRequestMessage_CreditCard) Reset() {
	*x = ChargeRequestMessage_CreditCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeRequestMessage_CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequestMessage_CreditCard) ProtoMessage() {}

func (x *ChargeRequestMessage_CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequestMessage_CreditCard.ProtoReflect.Descriptor instead.
func (*ChargeRequestMessage_CreditCard) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ChargeRequestMessage_CreditCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *ChargeRequestMessage_CreditCard) GetVerificationValue() string {
	if x != nil {
		return x.VerificationValue
	}
	return ""
}

func (x *ChargeRequestMessage_CreditCard) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *ChargeRequestMessage_CreditCard) GetExpMonth() ChargeRequestMessage_CreditCard_ExpMonth {
	if x != nil {
		return x.ExpMonth
	}
	return ChargeRequestMessage_CreditCard_JAN
}

func (x *ChargeRequestMessage_CreditCard) GetExpYear() string {
	if x != nil {
		return x.ExpYear
	}
	return ""
}

func (x *ChargeRequestMessage_CreditCard) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChargeRequestMessage_CreditCard) GetSkipThreeDSecureVerification() bool {
	if x != nil {
		return x.SkipThreeDSecureVerification
	}
	return false
}

type ChargeResponseMessage_ThreeDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RedirectUrl string `protobuf:"bytes,2,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
}

func (x *ChargeResponseMessage_ThreeDs) Reset() {
	*x = ChargeResponseMessage_ThreeDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeResponseMessage_ThreeDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeResponseMessage_ThreeDs) ProtoMessage() {}

func (x *ChargeResponseMessage_ThreeDs) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeResponseMessage_ThreeDs.ProtoReflect.Descriptor instead.
func (*ChargeResponseMessage_ThreeDs) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ChargeResponseMessage_ThreeDs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChargeResponseMessage_ThreeDs) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

var File_server_proto protoreflect.FileDescriptor

var file_server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x9a, 0x05, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x1a, 0xa4, 0x03, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x08, 0x65, 0x78, 0x70,
	0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x2e, 0x45, 0x78, 0x70, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x08, 0x65,
	0x78, 0x70, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x59, 0x65,
	0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x70, 0x59, 0x65, 0x61,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x42, 0x0a, 0x1c, 0x73, 0x6b, 0x69, 0x70, 0x54,
	0x68, 0x72, 0x65, 0x65, 0x44, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1c, 0x73,
	0x6b, 0x69, 0x70, 0x54, 0x68, 0x72, 0x65, 0x65, 0x44, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x76, 0x0a, 0x08, 0x45,
	0x78, 0x70, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x07, 0x0a, 0x03, 0x4a, 0x41, 0x4e, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x46, 0x45, 0x42, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x41, 0x52,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x50, 0x52, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4d,
	0x41, 0x59, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4a, 0x55, 0x4e, 0x10, 0x05, 0x12, 0x07, 0x0a,
	0x03, 0x4a, 0x55, 0x4c, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x55, 0x47, 0x10, 0x07, 0x12,
	0x07, 0x0a, 0x03, 0x53, 0x45, 0x50, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x43, 0x54, 0x10,
	0x09, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x4f, 0x56, 0x10, 0x0a, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x45,
	0x43, 0x10, 0x0b, 0x22, 0xab, 0x02, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x55, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x55, 0x72,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x74,
	0x68, 0x72, 0x65, 0x65, 0x44, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x68, 0x72, 0x65,
	0x65, 0x44, 0x73, 0x52, 0x07, 0x74, 0x68, 0x72, 0x65, 0x65, 0x44, 0x73, 0x1a, 0x43, 0x0a, 0x07,
	0x54, 0x68, 0x72, 0x65, 0x65, 0x44, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72,
	0x6c, 0x32, 0x55, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x47, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData = file_server_proto_rawDesc
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_rawDescData)
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_proto_goTypes = []interface{}{
	(ChargeRequestMessage_CreditCard_ExpMonth)(0), // 0: server.ChargeRequestMessage.CreditCard.ExpMonth
	(*ChargeRequestMessage)(nil),                  // 1: server.ChargeRequestMessage
	(*ChargeResponseMessage)(nil),                 // 2: server.ChargeResponseMessage
	(*ChargeRequestMessage_CreditCard)(nil),       // 3: server.ChargeRequestMessage.CreditCard
	(*ChargeResponseMessage_ThreeDs)(nil),         // 4: server.ChargeResponseMessage.ThreeDs
}
var file_server_proto_depIdxs = []int32{
	3, // 0: server.ChargeRequestMessage.creditCard:type_name -> server.ChargeRequestMessage.CreditCard
	4, // 1: server.ChargeResponseMessage.threeDs:type_name -> server.ChargeResponseMessage.ThreeDs
	0, // 2: server.ChargeRequestMessage.CreditCard.expMonth:type_name -> server.ChargeRequestMessage.CreditCard.ExpMonth
	1, // 3: server.PayService.Charge:input_type -> server.ChargeRequestMessage
	2, // 4: server.PayService.Charge:output_type -> server.ChargeResponseMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargeRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargeResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargeRequestMessage_CreditCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargeResponseMessage_ThreeDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_rawDesc = nil
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
