version: '3.9'
services:
  vault:
    image: vault:1.10.3
    container_name: vault
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/server.hcl

